// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241018095127_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspCoreApplication2023.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("memebershiptypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("memebershiptypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("genreId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("genreId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("WebApplication1.Models.Memebershiptype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("DiscountRate")
                        .HasColumnType("real");

                    b.Property<int>("DurationInMonth")
                        .HasColumnType("integer");

                    b.Property<int>("SignUpFee")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Memebershiptype");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Customer", b =>
                {
                    b.HasOne("AspCoreApplication2023.Models.Movie", null)
                        .WithMany("customers")
                        .HasForeignKey("MovieId");

                    b.HasOne("WebApplication1.Models.Memebershiptype", "memebershiptype")
                        .WithMany("customers")
                        .HasForeignKey("memebershiptypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("memebershiptype");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Movie", b =>
                {
                    b.HasOne("AspCoreApplication2023.Models.Genre", "genre")
                        .WithMany("movies")
                        .HasForeignKey("genreId");

                    b.Navigation("genre");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Genre", b =>
                {
                    b.Navigation("movies");
                });

            modelBuilder.Entity("AspCoreApplication2023.Models.Movie", b =>
                {
                    b.Navigation("customers");
                });

            modelBuilder.Entity("WebApplication1.Models.Memebershiptype", b =>
                {
                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
